server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: productService
          uri: lb://products-service
          predicates:
            - Path=/api/**

