server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
spring:
  data:
    mongodb:
      #      uri: mongodb://user:user@localhost:27017,localhost:27018,localhost:27019/shopdb
      uri: mongodb://user:user@mongodb1:27017,mongodb2:27018,mongodb3:27019/shopdb
